### ISSUE TITLE
setSelectedDataAsync vs. insertOoxml

### ISSUE THREAD

**Issue by Eichi78** [OfficeDev/Word-Add-in-Load-and-write-Open-XML#1]
Hi John,

first thanks for your work. Your example "setSText" (TextWithStyle.xml) works well, but if i try to insert the ooxml in a range (via range.insertOoxml), only plain text is inserted (style is ignored).

OK:
Office.context.document.setSelectedDataAsync(ooxmlString, { coercionType: 'ooxml' });

Not OK:
var rng = context.document.getSelection();
rng.insertOoxml(ooxmlString, Word.InsertLocation.replace);

Is this a bug?

Thanks in advance,
Eichi

**Comment by MIchaelMainer** [comment]
Hello Eichi78,

Thank you for bring this to our attention. Can you tell me the build number of Word? What error are you getting? 

Michael

**Comment by Eichi78** [comment]
Hi Michael,

thank you for your quick response.

_"Can you tell me the build number of Word?"_
Word 2016 (Windows, German) 16.0.6868.2060
Office.js: https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js

_"What error are you getting?"_
No error - the text is inserted as plain text. The style is not applied.

**LoadingAndWritingOOXML.js (Line 43)**
Instead of "_Office.context.document.setSelectedDataAsync(myXML, { coercionType: 'ooxml' });_" write the following code:

`Word.run(function (context) {`
 `var rng = context.document.getSelection();`
`rng.insertOoxml(myXML, Word.InsertLocation.replace);`
`return context.sync().then(function () {`
`console.log("success");`
`}).catch(function (error) {`
`console.log("error");`
`});`
`});`

The text will now inserted without the style "Heading 1".

Best regards,
Eichi

**Comment by MIchaelMainer** [comment]
Hello Eichi78,

Thank you for bringing this up!  This is a bug and I have repro. I haven't looked at the OOXML but the style is not being applied. 

```
// Run a batch operation against the Word object model.
Word.run(function (context) {

    var range = context.document.getSelection(); // select text with heading 1
    var body = context.document.body;
    var ooxml = range.getOoxml();

    return context.sync().then(function () {
        console.log('The OOXML read from the document was:  ' + ooxml.value);
    }).then(function () {
        body.insertOoxml(ooxml.value, 'End'); // the inserted text is not heading 1 as expected.
    }).then(context.sync);  
})
```

I'll be opening an issue with the folks who own the API. I'll close on this when I have more information. Thank you again for taking the time to report this.

**Comment by MIchaelMainer** [comment]
@Eichi78 this bug was fixed and checked in. I'm guessing that we'll see the fix in the product next month. Again, thank you for bringing this to our attention. 

UPDATE: this fix will be added to Word 2016. I think you should be able to see the fix next month.

**Comment by Eichi78** [comment]
Hi Michael

thank you very much!

Eichi
