### ISSUE TITLE
Example how to insert SVG image into Word document

### ISSUE THREAD

**Issue by raesche** [OfficeDev/Word-Add-in-Load-and-write-Open-XML#3]
Hi
Thanks for these very helpful examples. I use your sample code to insert a PNG image into an empty Word document by loading the SimpleImage.xml data. However I need to insert SVG images and tried to adopt the SimpleImage.xml file by changing the following lines:

1: Line #12
`<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image1.png"/>`
--> Set Target="media/image1.**svg**"

2: Line #37
`<pic:cNvPr id="6" name="logo_placeholder.png"/>`
-->Set name="logo_placeholder.**svg**"

3: Line #72
` <pkg:part pkg:name="/word/media/image1.png" pkg:contentType="image/png" pkg:compression="store">`
--> Set pkg:name="/word/media/image1.**svg**"
--> Set pkg:contentType="image/**svg+xml**" 

4: Line #73
`<pkg:binaryData>`
--> Replace data with my own SVG base 64 encoded content

After loading the modified XML file, an empty placeholder for the image is shown (icon for a broken image). If I save and convert the document to a ZIP file, I cannot find the svg image inside the media folder. 

Is there something I'm missing or is SVG not supported in this way? I tested the code with both Office 2016 and 365 and I can manually insert SVG images into Word documents without problems.

Are there other ways how SVG files or content can be added using the office.js API?

Thanks for any help & regards
Rashid

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
